services:
  - type: web
    name: atak-kulubu
    runtime: python
    buildCommand: pip install -r requirements.txt && flask init-db && flask seed-db
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: atak-db
          property: connectionString

databases:
  - name: atak-db
    databaseName: atak
    user: atak_user
